package cz.hlidacspoju.android.ui

import androidx.compose.runtime.compositionLocalOf
import cz.hlidacspoju.android.model.AppLanguage

/**
 * Minimal in-app localization. Mirrors the Windows app's LocalizationManager but adapted to
 * Compose: strings are looked up by key for the currently selected [AppLanguage] via [LocalStrings].
 * Czech and English are fully translated; Russian/German/French currently fall back to English
 * until translated (matching the Windows app's language list so users can already pick them).
 */
private val Cs = mapOf(
    "app_title" to "Hlídač spojů",
    "settings" to "Nastavení",
    "back" to "Zpět",
    "add_connection" to "Přidat spoj",
    "no_connections" to "Zatím nemáte žádné sledované spoje.",
    "not_scheduled_today" to "Na dnešek není nastaveno hlídání spoje",
    "no_current_departures" to "Žádné aktuální spoje v okně",
    "window_passed_today" to "Dnes již žádný zbývající spoj v nastaveném okně",
    "next_departure_on_day" to "Další spoj v nastaveném okně jede v %1\$s",
    "no_departure_found_in_window" to "V zadaném okně nenalezen žádný spoj",
    "delayed_on_time" to "Zpožděno: %1\$d, na čas: %2\$d",
    "delete" to "Smazat",
    "edit_connection" to "Upravit spoj",
    "stop" to "Zastávka",
    "line" to "Linka",
    "direction" to "Směr",
    "time_from" to "Od (HH:mm)",
    "time_to" to "Do (HH:mm)",
    "custom_name" to "Vlastní název (nepovinné)",
    "days_of_week" to "Dny v týdnu",
    "save" to "Uložit",
    "cancel" to "Zrušit",
    "skip" to "Přeskočit",
    "welcome_title" to "Vítejte v Hlídači spojů",
    "welcome_body" to "Aby aplikace mohla sledovat zpoždění, potřebuje bezplatný API klíč od Golemio (Pražská datová platforma).",
    "open_golemio_registration" to "Otevřít registraci Golemio",
    "golemio_api_key" to "Golemio API klíč",
    "finish" to "Dokončit",
    "poll_interval" to "Kontrola každých (sekund)",
    "check_now" to "Zkontrolovat nyní",
    "language" to "Jazyk",
    "theme" to "Motiv",
    "theme_system" to "Podle systému",
    "theme_light" to "Světlý",
    "theme_dark" to "Tmavý",
    "logging_enabled" to "Povolit logování (vypněte před publikováním)",
    "day_mon" to "Po", "day_tue" to "Út", "day_wed" to "St", "day_thu" to "Čt",
    "day_fri" to "Pá", "day_sat" to "So", "day_sun" to "Ne",
    "connection_detail" to "Detail spoje",
    "not_departed" to "Ještě nevyjelo",
    "close" to "Zavřít",
    "edit" to "Upravit",
    "notification_lead_time" to "Upozornit předem (minut)",
    "notification_channel_service_name" to "Sledování spojů",
    "notification_channel_delay_name" to "Zpoždění spojů",
    "notification_service_title" to "Hlídač spojů",
    "notification_service_text" to "Sledování zpoždění je aktivní",
    "notification_line_title" to "Linka %1\$s – %2\$s",
    "notification_delayed_text" to "Odjezd %1\$s naplánovaný na %2\$s má zpoždění %3\$d min. Očekávaný odjezd: %4\$s.",
    "notification_on_time_text" to "Odjezd %1\$s v %2\$s jede na čas.",
    "notification_other_on_time_suffix" to " Ostatní spoje této linky jedou na čas.",
    "notification_departed_text" to "Odjezd %1\$s v %2\$s právě vyjel ze zastávky."
)

private val En = mapOf(
    "app_title" to "Connection Watcher",
    "settings" to "Settings",
    "back" to "Back",
    "add_connection" to "Add connection",
    "no_connections" to "You have no watched connections yet.",
    "not_scheduled_today" to "Not scheduled for monitoring today",
    "no_current_departures" to "No current departures in this window",
    "window_passed_today" to "No more connections left in the configured window today",
    "next_departure_on_day" to "Next departure in the configured window is on %1\$s",
    "no_departure_found_in_window" to "No departure found in the configured window",
    "delayed_on_time" to "Delayed: %1\$d, on time: %2\$d",
    "delete" to "Delete",
    "edit_connection" to "Edit connection",
    "stop" to "Stop",
    "line" to "Line",
    "direction" to "Direction",
    "time_from" to "From (HH:mm)",
    "time_to" to "To (HH:mm)",
    "custom_name" to "Custom name (optional)",
    "days_of_week" to "Days of week",
    "save" to "Save",
    "cancel" to "Cancel",
    "welcome_title" to "Welcome to Hlídač spojů",
    "welcome_body" to "To track delays, the app needs a free API key from Golemio (Prague data platform).",
    "open_golemio_registration" to "Open Golemio registration",
    "golemio_api_key" to "Golemio API key",
    "finish" to "Finish",
    "skip" to "Skip",
    "poll_interval" to "Check every (seconds)",
    "check_now" to "Check now",
    "language" to "Language",
    "theme" to "Theme",
    "theme_system" to "System default",
    "theme_light" to "Light",
    "theme_dark" to "Dark",
    "logging_enabled" to "Enable logging (turn off before publishing)",
    "day_mon" to "Mon", "day_tue" to "Tue", "day_wed" to "Wed", "day_thu" to "Thu",
    "day_fri" to "Fri", "day_sat" to "Sat", "day_sun" to "Sun",
    "connection_detail" to "Connection detail",
    "not_departed" to "Not yet departed",
    "close" to "Close",
    "edit" to "Edit",
    "notification_lead_time" to "Notify ahead by (minutes)",
    "notification_channel_service_name" to "Connection monitoring",
    "notification_channel_delay_name" to "Connection delays",
    "notification_service_title" to "Hlídač spojů",
    "notification_service_text" to "Delay monitoring is active",
    "notification_line_title" to "Line %1\$s – %2\$s",
    "notification_delayed_text" to "Departure %1\$s scheduled for %2\$s is delayed by %3\$d min. Expected departure: %4\$s.",
    "notification_on_time_text" to "Departure %1\$s at %2\$s is on time.",
    "notification_other_on_time_suffix" to " Other departures on this line are on time.",
    "notification_departed_text" to "Departure %1\$s at %2\$s has just left the stop."
)

private val Ru = mapOf(
    "app_title" to "Наблюдатель за рейсами",
    "settings" to "Настройки",
    "back" to "Назад",
    "add_connection" to "Добавить рейс",
    "no_connections" to "У вас пока нет отслеживаемых рейсов.",
    "not_scheduled_today" to "Сегодня отслеживание не настроено",
    "no_current_departures" to "Нет текущих отправлений в этом окне",
    "window_passed_today" to "Сегодня больше нет рейсов в заданном окне",
    "next_departure_on_day" to "Следующий рейс в заданном окне: %1\$s",
    "no_departure_found_in_window" to "В заданном окне рейсы не найдены",
    "delayed_on_time" to "С опозданием: %1\$d, по расписанию: %2\$d",
    "delete" to "Удалить",
    "edit_connection" to "Изменить рейс",
    "stop" to "Остановка",
    "line" to "Линия",
    "direction" to "Направление",
    "time_from" to "От (ЧЧ:мм)",
    "time_to" to "До (ЧЧ:мм)",
    "custom_name" to "Своё название (необязательно)",
    "days_of_week" to "Дни недели",
    "save" to "Сохранить",
    "cancel" to "Отмена",
    "skip" to "Пропустить",
    "welcome_title" to "Добро пожаловать в Наблюдатель за рейсами",
    "welcome_body" to "Для отслеживания задержек приложению нужен бесплатный API-ключ Golemio (пражская платформа открытых данных).",
    "open_golemio_registration" to "Открыть регистрацию Golemio",
    "golemio_api_key" to "API-ключ Golemio",
    "finish" to "Готово",
    "poll_interval" to "Проверка каждые (секунд)",
    "check_now" to "Проверить сейчас",
    "language" to "Язык",
    "theme" to "Тема",
    "theme_system" to "Системная",
    "theme_light" to "Светлая",
    "theme_dark" to "Тёмная",
    "logging_enabled" to "Включить логирование (отключите перед публикацией)",
    "day_mon" to "Пн", "day_tue" to "Вт", "day_wed" to "Ср", "day_thu" to "Чт",
    "day_fri" to "Пт", "day_sat" to "Сб", "day_sun" to "Вс",
    "connection_detail" to "Детали рейса",
    "not_departed" to "Ещё не выехал",
    "close" to "Закрыть",
    "edit" to "Изменить",
    "notification_lead_time" to "Уведомлять заранее (минут)",
    "notification_channel_service_name" to "Отслеживание рейсов",
    "notification_channel_delay_name" to "Задержки рейсов",
    "notification_service_title" to "Наблюдатель за рейсами",
    "notification_service_text" to "Отслеживание задержек активно",
    "notification_line_title" to "Линия %1\$s – %2\$s",
    "notification_delayed_text" to "Отправление %1\$s, запланированное на %2\$s, задерживается на %3\$d мин. Ожидаемое отправление: %4\$s.",
    "notification_on_time_text" to "Отправление %1\$s в %2\$s идёт по расписанию.",
    "notification_other_on_time_suffix" to " Остальные рейсы этой линии идут по расписанию.",
    "notification_departed_text" to "Отправление %1\$s в %2\$s только что выехало с остановки."
)

private val De = mapOf(
    "app_title" to "Verbindungswächter",
    "settings" to "Einstellungen",
    "back" to "Zurück",
    "add_connection" to "Verbindung hinzufügen",
    "no_connections" to "Sie haben noch keine beobachteten Verbindungen.",
    "not_scheduled_today" to "Heute nicht überwacht",
    "no_current_departures" to "Keine aktuellen Abfahrten in diesem Zeitfenster",
    "window_passed_today" to "Heute keine verbleibenden Verbindungen im festgelegten Zeitfenster",
    "next_departure_on_day" to "Nächste Abfahrt im festgelegten Zeitfenster: %1\$s",
    "no_departure_found_in_window" to "Im festgelegten Zeitfenster wurde keine Abfahrt gefunden",
    "delayed_on_time" to "Verspätet: %1\$d, pünktlich: %2\$d",
    "delete" to "Löschen",
    "edit_connection" to "Verbindung bearbeiten",
    "stop" to "Haltestelle",
    "line" to "Linie",
    "direction" to "Richtung",
    "time_from" to "Von (HH:mm)",
    "time_to" to "Bis (HH:mm)",
    "custom_name" to "Eigener Name (optional)",
    "days_of_week" to "Wochentage",
    "save" to "Speichern",
    "cancel" to "Abbrechen",
    "skip" to "Überspringen",
    "welcome_title" to "Willkommen beim Verbindungswächter",
    "welcome_body" to "Um Verspätungen zu verfolgen, benötigt die App einen kostenlosen API-Schlüssel von Golemio (Prags offene Datenplattform).",
    "open_golemio_registration" to "Golemio-Registrierung öffnen",
    "golemio_api_key" to "Golemio-API-Schlüssel",
    "finish" to "Fertig",
    "poll_interval" to "Prüfung alle (Sekunden)",
    "check_now" to "Jetzt prüfen",
    "language" to "Sprache",
    "theme" to "Design",
    "theme_system" to "Systemstandard",
    "theme_light" to "Hell",
    "theme_dark" to "Dunkel",
    "logging_enabled" to "Protokollierung aktivieren (vor Veröffentlichung deaktivieren)",
    "day_mon" to "Mo", "day_tue" to "Di", "day_wed" to "Mi", "day_thu" to "Do",
    "day_fri" to "Fr", "day_sat" to "Sa", "day_sun" to "So",
    "connection_detail" to "Verbindungsdetails",
    "not_departed" to "Noch nicht abgefahren",
    "close" to "Schließen",
    "edit" to "Bearbeiten",
    "notification_lead_time" to "Im Voraus benachrichtigen (Minuten)",
    "notification_channel_service_name" to "Verbindungsüberwachung",
    "notification_channel_delay_name" to "Verbindungsverspätungen",
    "notification_service_title" to "Verbindungswächter",
    "notification_service_text" to "Verspätungsüberwachung ist aktiv",
    "notification_line_title" to "Linie %1\$s – %2\$s",
    "notification_delayed_text" to "Abfahrt %1\$s, geplant für %2\$s, hat %3\$d Min. Verspätung. Erwartete Abfahrt: %4\$s.",
    "notification_on_time_text" to "Abfahrt %1\$s um %2\$s ist pünktlich.",
    "notification_other_on_time_suffix" to " Andere Verbindungen dieser Linie sind pünktlich.",
    "notification_departed_text" to "Abfahrt %1\$s um %2\$s ist soeben von der Haltestelle abgefahren."
)

private val Fr = mapOf(
    "app_title" to "Surveillant de correspondances",
    "settings" to "Paramètres",
    "back" to "Retour",
    "add_connection" to "Ajouter une correspondance",
    "no_connections" to "Vous n'avez pas encore de correspondances surveillées.",
    "not_scheduled_today" to "Non surveillé aujourd'hui",
    "no_current_departures" to "Aucun départ actuel dans cette fenêtre",
    "window_passed_today" to "Plus aucune correspondance restante dans la fenêtre configurée aujourd'hui",
    "next_departure_on_day" to "Prochain départ dans la fenêtre configurée : %1\$s",
    "no_departure_found_in_window" to "Aucun départ trouvé dans la fenêtre configurée",
    "delayed_on_time" to "En retard : %1\$d, à l'heure : %2\$d",
    "delete" to "Supprimer",
    "edit_connection" to "Modifier la correspondance",
    "stop" to "Arrêt",
    "line" to "Ligne",
    "direction" to "Direction",
    "time_from" to "De (HH:mm)",
    "time_to" to "À (HH:mm)",
    "custom_name" to "Nom personnalisé (facultatif)",
    "days_of_week" to "Jours de la semaine",
    "save" to "Enregistrer",
    "cancel" to "Annuler",
    "skip" to "Ignorer",
    "welcome_title" to "Bienvenue dans Surveillant de correspondances",
    "welcome_body" to "Pour suivre les retards, l'application a besoin d'une clé API gratuite de Golemio (plateforme de données ouvertes de Prague).",
    "open_golemio_registration" to "Ouvrir l'inscription Golemio",
    "golemio_api_key" to "Clé API Golemio",
    "finish" to "Terminer",
    "poll_interval" to "Vérifier toutes les (secondes)",
    "check_now" to "Vérifier maintenant",
    "language" to "Langue",
    "theme" to "Thème",
    "theme_system" to "Système",
    "theme_light" to "Clair",
    "theme_dark" to "Sombre",
    "logging_enabled" to "Activer la journalisation (désactiver avant publication)",
    "day_mon" to "Lu", "day_tue" to "Ma", "day_wed" to "Me", "day_thu" to "Je",
    "day_fri" to "Ve", "day_sat" to "Sa", "day_sun" to "Di",
    "connection_detail" to "Détail de la correspondance",
    "not_departed" to "Pas encore parti",
    "close" to "Fermer",
    "edit" to "Modifier",
    "notification_lead_time" to "Avertir à l'avance (minutes)",
    "notification_channel_service_name" to "Surveillance des correspondances",
    "notification_channel_delay_name" to "Retards des correspondances",
    "notification_service_title" to "Surveillant de correspondances",
    "notification_service_text" to "La surveillance des retards est active",
    "notification_line_title" to "Ligne %1\$s – %2\$s",
    "notification_delayed_text" to "Le départ %1\$s prévu à %2\$s a %3\$d min de retard. Départ prévu : %4\$s.",
    "notification_on_time_text" to "Le départ %1\$s à %2\$s est à l'heure.",
    "notification_other_on_time_suffix" to " Les autres correspondances de cette ligne sont à l'heure.",
    "notification_departed_text" to "Le départ %1\$s à %2\$s vient de quitter l'arrêt."
)

private val translations: Map<AppLanguage, Map<String, String>> = mapOf(
    AppLanguage.CZECH to Cs,
    AppLanguage.ENGLISH to En,
    AppLanguage.RUSSIAN to Ru,
    AppLanguage.GERMAN to De,
    AppLanguage.FRENCH to Fr
)

class Strings(private val language: AppLanguage) {
    fun get(key: String): String =
        translations[language]?.get(key) ?: Cs[key] ?: key

    fun get(key: String, vararg args: Any): String =
        String.format(get(key), *args)

    operator fun invoke(key: String): String = get(key)
}

val LocalStrings = compositionLocalOf { Strings(AppLanguage.CZECH) }
